automatic_reinitialization: True
pipeline_is_stereo: False

max_fts: 180
max_n_kfs: 5
quality_min_fts: 10
quality_max_drop_fts: 140

map_scale: 50

T_world_imuinit/qx: 0.0035622019159513617
T_world_imuinit/qy: -0.011363129110865712
T_world_imuinit/qz: 0.33710546776135597
T_world_imuinit/qw: 0.9413915729491725

kfselect_criterion: DOWNLOOKING
kfselect_numkfs_upper_thresh: 160
kfselect_numkfs_lower_thresh: 60
kfselect_min_dist_metric: 10.0
kfselect_min_angle: 10
kfselect_min_disparity: 10
update_seeds_with_old_keyframes: True

kfselect_backend_max_time_sec: -1.0
kfselect_min_num_frames_between_kfs: 20

img_align_est_illumination_gain: true
img_align_est_illumination_offset: true
depth_filter_affine_est_offset: true
depth_filter_affine_est_gain: false
reprojector_affine_est_offset: true
reprojector_affine_est_gain: false

# Handle tracking loss
global_map_timeout_sec: 5.0

init_min_features: 15
init_min_disparity: 5

grid_size: 25
n_pyr_levels: 4
detector_threshold_primary: 12
detector_threshold_secondary: 300 # Edgelet detector threshold
detector_threshold_shitomasi: 200 # Map Point detector threshold

img_align_max_level: 4
img_align_min_level: 1

use_async_reprojectors: False # For stereo, change it to True for multithreading.
reprojector_max_n_kfs: 7
scan_epi_unit_sphere: False # for wide angle lens, set it to True.
reproject_unconverged_seeds: True
max_unconverged_seeds_ratio: 0.4
reprojector_max_fixed_landmarks: 200
reprojector_max_n_global_kfs: 200
reprojector_fixed_lm_grid_size: 25 # 25

poseoptim_thresh: 1.8
poseoptim_using_unit_sphere: False # For wide angle lens, set it to True

seed_convergence_sigma2_thresh: 150
mappoint_convergence_sigma2_thresh: 300

relocalization_max_trials: 10

use_imu: false
poseoptim_prior_lambda: 0.001 # Gyroscope prior in pose optimization
img_align_prior_lambda_rot: 0.01
img_align_prior_lambda_trans: 0.1 # Constant velocity assumption prior in sparse image alignment

publish_every_nth_dense_input: 5

publish_marker_scale: 0.5
publish_active_kfs: True

max_depth_inv: 0.05
min_depth_inv: 1.0
mean_depth_inv: 0.3

use_ceres_backend: false
ceres_verbose: false
ceres_marginalize: true
ceres_num_iterations: 3
ceres_num_imu_frames: 3
ceres_num_threads: 4
ceres_max_iteration_time: -1 # soft limit, set to -1 to deactivate
publish_marker_scale_backend: 0.5 # set to -1 to deactivate visualization of landmarks
backend_only_use_corners: false
backend_scale_stable_thresh: 0.07
ceres_max_fixed_landmarks: 80

backend_refine_extrinsics: false
backend_extrinsics_pos_sigma_meter: 0.02
backend_extrinsics_rot_sigma_deg: 1.0

use_outlier_rejection: true
outlier_rejection_px_threshold: 1.8

backend_use_zero_motion_detection: true
backend_zero_motion_check_n_frames: 30
zero_motion_px_diff_threshold: 0.2 # decrease with lower resolution
zero_motion_ratio_moving_pixels_threshold: 0.1
zero_motion_min_number_correspondences: 30
zero_motion_max_features_to_check: 30
zero_motion_sigma: 0.1

ceres_remove_marginalization_term_after_loop: true
ceres_recalculate_imu_terms_after_loop: true

ceres_remove_fixation_min_num_fixed_points: 10

runlc: True
voc_name: voc_GEN_8X4.yml.gz
alpha: 0.8
beta: 0.8
frames_to_ignore: 100
scale_retrieval_approach: None
bow_thresh: 0.65
gv_3d_inlier_thresh: 0.5
min_num_3d: 20
orb_dist_thresh: 300
gv_2d_match_thresh: 0.3
use_opengv: true
enable_image_logging: false
image_log_base_path: /tmp/loopclosure_log/
ransac3d_inlier_percent: 60

proximity_dist_ratio: 0.02
proximity_offset: 1.0

global_map_type: ExternalGlobalMap

force_correction_dist_thresh_meter: 0.1

##############################
# Global map
##############################
depth_filter_extra_map_points: True
max_map_fts: 300
reprojector_use_kfs_from_global_map: True
refine_extrinsics: True

use_global_map: False

# initialization
gm_init_min_frame_opt: 15
gm_init_min_lm_obs_frame: 8
gm_use_smart_factor: False
gm_debug_fix_all_poses: False
gm_print_stdcout: False
gm_use_imu: True
gm_use_thread: True
gm_verbose: False
gm_only_add_every_n: -1
gm_optimize_every_n: -1
gm_point_stable_thresh_meter: -1.0
gm_inc_version_stable_ratio: -1.0

# reobsrevation
gm_add_reprojected_fixed_landmark: true
gm_max_reprojected_fixed_landmark_each_frame: 60
gm_ignore_redundant_landmarks: false
gm_ignore_grid_size: 15
gm_fix_lm_reobs_threshold: -1

# point adding and fixation
gm_min_num_obs: 3
gm_pt_cond_thresh: -1
gm_pt_sigma_thresh: 0.5
gm_max_point_age: 5
gm_min_parallax_deg: 1.0
gm_add_range_prior_to_good_pt: True
gm_use_edgelet: True
gm_use_map_point: True
gm_map_point_min_obs: 5

# frame: fix with respect to previous one
gm_use_relative_pose_fixation: True
gm_relative_prior_with_imu_min_time_sec: -1.0
gm_frame_fixation_release_check: False
gm_relative_min_common_obs: 10
gm_relative_release_min_common_obs: 40
gm_relative_pos_sigma_meter: 0.1
gm_relative_rot_sigma_deg: 5.0

# query
gm_query_frame_min_3d_points: 10

# gtsam related
ba_use_bearing_factor: True
ba_pos_sigma_meter: 0.000001
ba_rot_sigma_degree: 0.000001
ba_init_roll_pitch_sigma_degree: 10.0
ba_point_sigma_meter: 0.0001

ba_max_iterations_per_update: 20
ba_min_iterations_per_update: 5
ba_max_time_sec_per_update: 5.0

ba_use_robust_px_noise: True
isam_relinearize_thresh: 0.01
isam_relinearize_skip: 5
isam_wildfire_thresh: 0.001
isam_optimization_method: GaussNewton
ba_smart_reproj_outlier_thresh_px: 10.0
